---
##################
# INSTALL PIP 
##################
- name: install python-pip package
  apt: name={{ item }} state=present force=yes
  with_items:
    - python-pip
- name: shutdown ufw
  shell: ufw disable
- name: mkdir /root/.pip
  file: path=/root/.pip state=directory
- name: update pip.conf
  template: src=pip.conf dest=/root/.pip/pip.conf
- name: update pip
  shell: pip install -U pip==9.0.1

###########################
# INSTALL Dependent PACKAGES
###########################
- name: install dependent packages
  apt: name={{ item }} state=present force=yes
  with_items:
    - python-dev
    - libffi-dev
    - gcc
    - libssl-dev
    - git
    - apt-transport-https
    - ca-certificates
    - gdisk
- name: install keyserver
  shell: apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
- name: install linux-image-extra
  shell: sudo apt-get install linux-image-extra-$(uname -r)
- name: copy docker-key
  copy: src=docker-key dest=/tmp
- name:  add docker-key
  shell: sudo apt-key add /tmp/docker-key
- name: add-apt-repository
  shell: sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
- name: update docker cache
  apt: update_cache=yes

- name: pip install docker
  pip:
    name: docker
    #version: 1.10.6
- name: pip install packages
  pip:
    name: "{{ item }}"
  with_items:
#    - ansible
  #  - kolla
    - netifaces
    - IPy

#########################
#INSTALL DOCKER
#########################
- name: install docker-ce
  apt: name=docker-ce state=present force=yes

- name: mkdir docker.service.d
  file: path=/etc/systemd/system/docker.service.d recurse=yes state=directory

- name: copy kolla.conf
  template: src=kolla.conf dest=/etc/systemd/system/docker.service.d/kolla.conf

- name: restart docker service
  service: name=docker state=restarted

- name: Set mountinfo flag for neutron
  shell: mount --make-shared /run

- name: registry image department
  lineinfile:
    dest: /lib/systemd/system/docker.service
    regexp: ^ExecStart=/usr/bin/dockerd -H unix://
    line: 'ExecStart=/usr/bin/dockerd -H unix:// --insecure-registry {{ harbor_ip }}'

- name: restart docker service
  systemd:
    name: docker
    daemon_reload: yes
    state: restarted

