---
- name: install ntpdate
  apt: name=ntpdate state=present

- name: stop ntp service
  systemd: name=ntp state=stopped enabled=no
  ignore_errors: True

- name: 时区调整
  shell: cp /usr/share/zoneinfo/Asia/Shanghai  /etc/localtime

- name: update ntp time
  shell: ntpdate {{ ntp_nodes }}
  ignore_errors: True

- name: add cron job
  cron: 
    name: "update ntp"
    minute: "0"
    hour: "2"
    job: "/usr/sbin/ntpdate {{ ntp_nodes }} >> /tmp/ntp.log 2>&1"
